import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="gird grid-cols-2">
      <SideBar />
      <div className="w-5/6 absolute right-0">
        <div className="p-3 w-full shadow-md text-gray-900 bg-gray-100">
          <div className="font-semibold text-lg">Spaces / Create</div>
        </div>
        {children}
      </div>
    </div>
  );
}
